name: "Nueva Publicación"
description: "Añadir un enlace a un artículo publicado en un medio externo"
title: "[Publicación]: "
labels: ["nueva-publicacion"]
body:
  - type: markdown
    attributes:
      value: |
        ## Nueva Publicación
        Rellena los campos para añadir un enlace a un artículo publicado en un medio externo.

  - type: input
    id: title
    attributes:
      label: Título
      description: Título del artículo
      placeholder: "Ej: El patrimonio amenazado de Caravaca"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Descripción
      description: Resumen breve del artículo (1-2 frases)
      placeholder: "Ej: Artículo sobre los edificios históricos en riesgo de desaparición"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Fecha
      description: Fecha de publicación (AAAA-MM-DD). Dejar vacío para usar la fecha de hoy.
      placeholder: "2025-01-15"
    validations:
      required: false

  - type: input
    id: source
    attributes:
      label: Fuente
      description: Nombre del medio donde se publicó
      placeholder: "El Noroeste Digital"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: Enlace al artículo original
      placeholder: "https://elnoroestedigital.com/..."
    validations:
      required: true
