name: "Nuevo Trabajo"
description: "Crear un nuevo proyecto de arquitectura o conservación"
title: "[Trabajo]: "
labels: ["nuevo-trabajo"]
body:
  - type: markdown
    attributes:
      value: |
        ## Nuevo Trabajo
        Rellena los campos para añadir un proyecto. Puedes arrastrar imágenes directamente en el campo de imagen.

  - type: input
    id: title
    attributes:
      label: Título
      description: Nombre del proyecto
      placeholder: "Ej: Rehabilitación Casa de la Virgen"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Descripción
      description: Descripción breve del proyecto (1-2 frases, sin imágenes)
      placeholder: "Ej: Proyecto de rehabilitación de una casa tradicional del siglo XVIII"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Fecha
      description: Fecha del proyecto (AAAA-MM-DD). Dejar vacío para usar la fecha de hoy.
      placeholder: "2025-01-15"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Categoría
      description: Tipo de proyecto
      options:
        - Rehabilitación
        - Restauración
        - Obra nueva
        - Proyecto
        - Dirección de obra
        - Consultoría
        - Investigación
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Ubicación
      description: Ciudad y región del proyecto
      placeholder: "Caravaca de la Cruz, Murcia"
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Año
      description: Año o rango de años del proyecto
      placeholder: "2025 o 2020-2024"
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: Imagen destacada
      description: Arrastra aquí la imagen del proyecto o pega una URL.
      placeholder: "Arrastra una imagen aquí..."
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: Contenido
      description: |
        Descripción detallada del proyecto. Puedes usar Markdown (## para títulos, **negrita**, *cursiva*, etc.)

        **Imagen con texto:** Para alinear una imagen junto a texto, usa:
        - `{% media(align="left") %}` - imagen a la izquierda, texto a la derecha
        - `{% media(align="right") %}` - imagen a la derecha, texto a la izquierda

        Ejemplo:
        ```
        {% media(align="left") %}
        ![](url-imagen.jpg)

        Texto que aparece junto a la imagen.
        {% end %}
        ```
      placeholder: |
        ## Descripción del proyecto

        Escribe aquí la descripción detallada...

        {% media(align="left") %}
        ![](arrastra-imagen-aqui.jpg)

        Detalle técnico junto a la imagen.
        {% end %}

        ## Metodología

        Describe la metodología empleada...
    validations:
      required: false
