name: "Nueva Investigación"
description: "Crear una nueva publicación académica o investigación"
title: "[Investigación]: "
labels: ["nueva-investigacion"]
body:
  - type: markdown
    attributes:
      value: |
        ## Nueva Investigación
        Rellena los campos para añadir una publicación académica.

  - type: input
    id: title
    attributes:
      label: Título
      description: Título de la investigación
      placeholder: "Ej: Perspectivas del agua en la arquitectura"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Resumen o abstract de la investigación (solo texto, sin imágenes)
      placeholder: "Ej: Este artículo analiza el papel del agua en la arquitectura tradicional..."
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Fecha
      description: Fecha de publicación (AAAA-MM-DD). Dejar vacío para usar la fecha de hoy.
      placeholder: "2025-01-15"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Tipo de publicación
      options:
        - Article
        - Book
        - Conference Paper
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Año
      description: Año de publicación o rango de años del proyecto
      placeholder: "2025 o 2020-2024"
    validations:
      required: true

  - type: input
    id: coauthors
    attributes:
      label: Coautores
      description: Nombres de coautores separados por coma (opcional)
      placeholder: "Juan García, María López"
    validations:
      required: false

  - type: input
    id: link_url
    attributes:
      label: Enlace
      description: URL de ResearchGate u otro enlace a la publicación (opcional)
      placeholder: "https://www.researchgate.net/publication/..."
    validations:
      required: false
