name: "Nuevo Artículo"
description: "Crear un nuevo artículo o reflexión"
title: "[Artículo]: "
labels: ["nuevo-articulo"]
body:
  - type: markdown
    attributes:
      value: |
        ## Nuevo Artículo
        Rellena los campos para crear un nuevo artículo. Puedes arrastrar imágenes directamente en el campo de imagen.

  - type: input
    id: title
    attributes:
      label: Título
      description: El título del artículo
      placeholder: "Ej: Patrimonio rural y despoblación"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Descripción
      description: Resumen breve del artículo (1-2 frases, sin imágenes)
      placeholder: "Ej: Reflexión sobre el impacto de la despoblación en el patrimonio rural español"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Fecha
      description: Fecha de publicación (AAAA-MM-DD). Dejar vacío para usar la fecha de hoy.
      placeholder: "2025-01-15"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Categoría
      description: Tipo de artículo
      options:
        - Patrimonio
        - Reflexiones
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: Imagen destacada
      description: Arrastra aquí la imagen o pega una URL. La imagen aparecerá en la tarjeta del artículo.
      placeholder: "Arrastra una imagen aquí..."
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: Contenido
      description: |
        El contenido completo del artículo. Puedes usar Markdown (## para títulos, **negrita**, *cursiva*, etc.)

        **Imagen con texto:** Para alinear una imagen junto a texto, usa:
        - `{% media(align="left") %}` - imagen a la izquierda, texto a la derecha
        - `{% media(align="right") %}` - imagen a la derecha, texto a la izquierda

        Ejemplo:
        ```
        {% media(align="left") %}
        ![](url-imagen.jpg)

        Texto que aparece junto a la imagen.
        {% end %}
        ```
      placeholder: |
        ## Primera sección

        Escribe aquí el contenido...

        {% media(align="left") %}
        ![](arrastra-imagen-aqui.jpg)

        Texto que aparece a la derecha de la imagen.
        {% end %}

        ## Segunda sección

        Continúa escribiendo...
    validations:
      required: false
